"use client";

import { useState } from "react";
import type { ClientAccount, ScoreValue } from "@/lib/types";
import { scoreOptions, writeSeedOverride } from "@/lib/health-utils";

export type SavedScoreData = {
  clientId: string;
  weekStart: string;
  currentScore: ScoreValue;
  predictiveScore: ScoreValue;
  notes: string;
  actions: string;
};

type ScoreEntryFormProps = {
  selectedClient: ClientAccount;
  currentWeekStart: string;
  dataSource: "supabase" | "seed";
  onSave: (data: SavedScoreData) => void;
};

export function ScoreEntryForm({
  selectedClient,
  currentWeekStart,
  dataSource,
  onSave,
}: ScoreEntryFormProps) {
  const weekEntry = selectedClient.healthHistory.find(
    (w) => w.weekStart === currentWeekStart,
  );

  const [currentScore, setCurrentScore] = useState<ScoreValue | null>(
    weekEntry?.currentScore ?? null,
  );
  const [predictiveScore, setPredictiveScore] = useState<ScoreValue | null>(
    weekEntry?.predictiveScore ?? null,
  );
  const [notes, setNotes] = useState(weekEntry?.notes ?? "");
  const [actions, setActions] = useState(weekEntry?.actions ?? "");
  const [status, setStatus] = useState("");
  const [isGeneratingActions, setIsGeneratingActions] = useState(false);

  async function saveWeeklyScore() {
    if (currentScore === null || predictiveScore === null) {
      setStatus("Please select both Current and Predictive scores.");
      return;
    }
    if (predictiveScore < 5 && actions.trim().length === 0) {
      setStatus("Actions are required when Predictive Score is below 5.");
      return;
    }

    if (dataSource === "seed") {
      writeSeedOverride({
        clientId: selectedClient.id,
        weekStart: currentWeekStart,
        currentScore,
        predictiveScore,
        notes: notes.trim(),
        actions: actions.trim(),
      });
      onSave({
        clientId: selectedClient.id,
        weekStart: currentWeekStart,
        currentScore,
        predictiveScore,
        notes: notes.trim(),
        actions: actions.trim(),
      });
      setStatus("Saved locally (seed mode).");
      return;
    }

    const response = await fetch("/api/scores", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        clientId: selectedClient.id,
        weekStart: currentWeekStart,
        currentScore,
        predictiveScore,
        notes,
        actions,
      }),
    });

    if (!response.ok) {
      const payload = (await response.json().catch(() => ({}))) as {
        error?: string;
        details?: string;
      };
      setStatus(
        payload.details
          ? `${payload.error ?? "Could not save score."} (${payload.details})`
          : (payload.error ?? "Could not save score in Supabase."),
      );
      return;
    }

    onSave({
      clientId: selectedClient.id,
      weekStart: currentWeekStart,
      currentScore,
      predictiveScore,
      notes: notes.trim(),
      actions: actions.trim(),
    });
    setStatus("Saved to Supabase.");
  }

  async function generateActions() {
    if (predictiveScore === null) {
      setStatus("Set a predictive score first.");
      return;
    }

    setIsGeneratingActions(true);
    setStatus("");
    try {
      const response = await fetch("/api/suggest-actions", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          clientName: selectedClient.name,
          currentScore,
          predictiveScore,
          notes,
        }),
      });
      const payload = (await response.json()) as {
        suggestions: string[];
        source: "openai" | "heuristic";
      };
      setActions(payload.suggestions.map((line) => `- ${line}`).join("\n"));
      setStatus(
        payload.source === "openai"
          ? "Suggested actions generated by AI."
          : "Suggested actions generated from fallback logic.",
      );
    } catch {
      setStatus("Could not generate suggestions. Try again.");
    } finally {
      setIsGeneratingActions(false);
    }
  }

  return (
    <section className="rounded-xl bg-white p-4 shadow-sm ring-1 ring-slate-200 md:col-span-2 lg:col-span-1">
      <h2 className="text-base font-semibold">Weekly Score Entry</h2>
      <div className="mt-3">
        <p className="text-sm text-slate-600">
          <span className="font-medium text-slate-900">
            {selectedClient.name}
          </span>{" "}
          ({selectedClient.coachTeam})
        </p>

        <div className="mt-4 grid gap-4 sm:grid-cols-2">
          <div>
            <p className="text-sm font-medium">Current Score (this week)</p>
            <div className="mt-2 flex flex-wrap gap-2">
              {scoreOptions.map((score) => (
                <button
                  key={`current-${score}`}
                  onClick={() => setCurrentScore(score)}
                  className={`min-w-[2.25rem] rounded-md px-3 py-1.5 text-sm font-medium ${
                    currentScore === score
                      ? "bg-slate-900 text-white"
                      : "bg-slate-100 text-slate-700 hover:bg-slate-200"
                  }`}
                >
                  {score}
                </button>
              ))}
            </div>
          </div>
          <div>
            <p className="text-sm font-medium">
              Predictive Score (next week)
            </p>
            <div className="mt-2 flex flex-wrap gap-2">
              {scoreOptions.map((score) => (
                <button
                  key={`predictive-${score}`}
                  onClick={() => setPredictiveScore(score)}
                  className={`min-w-[2.25rem] rounded-md px-3 py-1.5 text-sm font-medium ${
                    predictiveScore === score
                      ? "bg-slate-900 text-white"
                      : "bg-slate-100 text-slate-700 hover:bg-slate-200"
                  }`}
                >
                  {score}
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="mt-4">
          <label className="text-sm font-medium">Notes</label>
          <textarea
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            rows={4}
            placeholder="Context from this week (delivery, stakeholder sentiment, risks)..."
            className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 text-sm outline-none focus:border-slate-500"
          />
        </div>

        <div className="mt-4">
          <div className="flex items-center justify-between">
            <label className="text-sm font-medium">
              Actions to move Predictive Score to 5
            </label>
            <button
              onClick={() => void generateActions()}
              disabled={isGeneratingActions}
              className="rounded-md border border-slate-300 px-2 py-1 text-xs font-medium text-slate-700 hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {isGeneratingActions ? "Generating..." : "Suggest with AI"}
            </button>
          </div>
          <textarea
            value={actions}
            onChange={(e) => setActions(e.target.value)}
            rows={5}
            placeholder="Required if predictive score is below 5."
            className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 text-sm outline-none focus:border-slate-500"
          />
        </div>

        {status && (
          <p className="mt-4 text-center text-sm text-slate-600">{status}</p>
        )}

        <div className="mt-3 text-center">
          <button
            onClick={() => void saveWeeklyScore()}
            className="rounded-md bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700"
          >
            Save Weekly Score
          </button>
        </div>
      </div>
    </section>
  );
}
